### ISSUE TITLE
[QUESTION] External samples don't work

### ISSUE THREAD

**Issue by mokraemer** [horstoeko/zugferdublbridge#5] opened 2024-12-19 11:34 UTC
I've tested some examples from
[Quba-Samples](https://quba-viewer.org/wp-content/uploads/2024/09/samples.zip) and
[Testsuite](https://github.com/itplr-kosit/xrechnung-testsuite/tree/master/src/test)

while importing/converting I get the error:
"The submitted profile urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0 is not supported"

But if this is part of many testsuits, I guess this should be supported.

A few more errors:

- UBL-CreditNote-2.1-Example.ubl.xml	: The document is not a valid UBL document

- EN16931_1_Teilrechnung.ubl.xml, EN16931_2_Teilrechnung.ubl.xml,... 	The submitted profile urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0 is not supported

- 04.01a-INVOICE_ubl....	The submitted profile urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0 is not supported

**Comment by horstoeko** [comment] 2024-12-19 11:38
Hi @mokraemer,

No. This is definitely not a bug. The focus of the module is on supporting the profiles supported in Germany that have a CII counterpart. I don't know what this profile is.

Kind regards

**Comment by mokraemer** [comment] 2024-12-19 12:26
I guess you are more involved into this topic.
I guess we will see in the near future if this is used, when it is available as samples in german testsuites.

**Comment by horstoeko** [comment] 2024-12-19 12:40
Hi @mokraemer,

some of the KOSiT test files are deliberately incorrect. Presumably people also want to test the negative cases. As far as point 1 is concerned, I have not yet seen such a document in the context of the XRechnung, as essential elements are missing there. Point 2 as well. Point 3 should actually be “urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0” according to the specification. 

I would say we will stay in contact about this. I'll close this issue for now and say goodbye to my vacation... ;-)

Kind regards

**Closed by horstoeko** 2024-12-19 12:40 UTC
Labels: question
